version: '3.8'
services:
  rails:
    build: .
    command: rails s -b 0.0.0.0
    container_name: diario-de-viagem
    ports:
      - 3000:3000
    links:
      - db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .:/opt/app
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - diario_de_viagem_data:/var/lib/postgresql/data
volumes:
  diario_de_viagem_data:
